// Code generated by "stringer -type=SectionID -trimprefix=Sect"; DO NOT EDIT.

package noxsave

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SectAttrib-2]
	_ = x[SectStatus-3]
	_ = x[SectInventory-4]
	_ = x[SectFieldGuide-8]
	_ = x[SectSpellbook-5]
	_ = x[SectEnchantment-6]
	_ = x[SectJournal-9]
	_ = x[SectGame-10]
	_ = x[SectPAD-11]
	_ = x[SectGUI-7]
	_ = x[SectFileInfo-1]
	_ = x[SectMusic-12]
}

const _SectionID_name = "FileInfoAttribStatusInventorySpellbookEnchantmentGUIFieldGuideJournalGamePADMusic"

var _SectionID_index = [...]uint8{0, 8, 14, 20, 29, 38, 49, 52, 62, 69, 73, 76, 81}

func (i SectionID) String() string {
	i -= 1
	if i >= SectionID(len(_SectionID_index)-1) {
		return "SectionID(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _SectionID_name[_SectionID_index[i]:_SectionID_index[i+1]]
}
